Changed Source.type to String
elbwalker/walker.js pull request #249
Opened 2023-07-21 00:50 UTC by wintercodeNKJJ

Closes issue #194

**file:**
`src > types > elbwalker.dts`  (line 122)

**Changes:**
```diff
interface Source {
+   type: string;
-    type: SourceType;
    ...
  }
```
**file:**
`src > elbwalker.ts`  (line 335)

```diff
    const source = {
+    type: 'web',
-     type: IElbwalker.SourceType.Web,
      id: window.location.href,
      previous_id: document.referrer,
    };
```

2023-07-26 15:12 UTC, alexanderkirtzel requested changes
Please keep in mind to also update the overall `README.md` with the new structured event format.
And is it possible to merge in `develop` branch?

2023-07-26 15:12 UTC, alexanderkirtzel commented on src/elbwalker.ts
> +      type: 'web',
I'd prefer to have a centralized place for const values.
The current status with const enum in types isn't good, too (see #193 )
But right now we'd have unused `const enum SourceType` in `elbwalker.d.ts`.

Why not just switching `Web = 1` to `Web = 'web'`?

2023-07-26 15:12 UTC, alexanderkirtzel commented on src/types/elbwalker.d.ts
> +    type: string;
What about the `elbwalker.test.ts` isn't there a test to check that it has to be 'web'? Before it was `1`. It's either not working, or we need to add/edit a test for this

2023-07-27 03:10 UTC, wintercodeNKJJ commented on src/elbwalker.ts
> +      type: 'web',
this is what I obtain as result when doing that
```bash
Types of property 'type' are incompatible.
        Type 'string' is not assignable to type 'SourceType.Web'
```

2023-08-08 10:09 UTC, merged