Elb prefix changeable
elbwalker/walker.js pull request #53
Opened 2022-05-23 17:50 UTC by Blubasur

2022-05-27 07:56 UTC, alexanderkirtzel requested changes
Maybe config.prefix should be required to skip the isset part?
Let me know what to update on elb-types

2022-05-27 07:56 UTC, alexanderkirtzel commented on src/elbwalker.ts
> +  if (config.prefix) {
by setting a default parameter it'll alway be set, but I guess TS isn't happy here.
Also initHandler should always be called to work properly.
Try sth like `const prefix = config.prefix || 'elb'`

2022-05-27 07:56 UTC, alexanderkirtzel commented on src/elbwalker.ts
> +  if (elbwalker.config.prefix === undefined) {
if (!elbwalker.config.prefix)

2022-05-27 07:56 UTC, alexanderkirtzel commented on src/elbwalker.ts
> +    elbwalker.config.prefix = 'elb';
const prefix = config.prefix || 'elb'

2022-05-27 07:56 UTC, alexanderkirtzel commented on src/elbwalker.ts
> -
nooooo 😱

2022-05-27 07:56 UTC, alexanderkirtzel commented on src/elbwalker.ts
> +    elbwalker.config.prefix = 'elb';
`const prefix = config.prefix || 'elb'`

2022-05-27 07:56 UTC, alexanderkirtzel commented on src/elbwalker.ts
> +  if (elbwalker.config.prefix) {
nope

2022-05-27 07:56 UTC, alexanderkirtzel commented on src/elbwalker.ts
> +  if (elbwalker.config.prefix) {
nope

2022-05-27 07:56 UTC, alexanderkirtzel commented on src/lib/handler.ts
> +            if (elbwalker.config.prefix === undefined) {
Feel free to ask before pr a "no good solution" :D

2022-05-27 10:34 UTC, Blubasur commented
fixed requested changes

2022-06-01 13:25 UTC, alexanderkirtzel approved these changes
noice

2022-06-01 13:25 UTC, merged